# Generated by Django 3.2.5 on 2023-08-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type_file',
            field=models.CharField(choices=[('img', 'IMG'), ('music', 'MUSIC'), ('video', 'VIDEO'), ('file', 'FILE'), ('other', 'OTHER')], default='other', max_length=100),
        ),
    ]
